version: "3.7"
services:
  storify-mdb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: storify_root
      MYSQL_DATABASE: storify_db_local
      MYSQL_USER: storify_user
      MYSQL_PASSWORD: storify_pass
    ports:
      - '3307:3306'

    volumes:
      - ./init:/docker-entrypoint-initdb.d