spring:
  application:
    name: storify
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate #do not change this value
  datasource:
    url: jdbc:mariadb://localhost:3307/storify_db_local
    username: storify_user
    password: storify_pass
    driver-class-name: org.mariadb.jdbc.Driver
  mail:
    host: smtp.yandex.ru
    username: storify@yandex.ru
    password: Mbicycle.com
    port: 465
    protocol: smtps

security:
  jwt-secret: storify

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://storify.cd1b0g4crtcb.us-east-1.rds.amazonaws.com:3306/storify_db